### ISSUE TITLE
mvn error

### ISSUE THREAD

**Issue by rajesh99** [billy1380/blogwt#54]
Hi,
I get the following error while doing 'mvn package'

[ERROR] Failed to execute goal on project blogwt: Could not resolve dependencies for project com.willshex:blogwt:war:0v4: The following artifacts could not be resolved: org.commonjava.googlecode.markdown4j:markdown4j-gwt:jar:1.1-SNAPSHOT, org.commonjava.googlecode.emoji:emoji-gwt:jar:1.1, gson:gson-gwt:jar:1.0, com.googlecode.gwtupload:gwtupload-gae:jar:1.0.4-SNAPSHOT, com.willshex:willshex-utility:jar:1.0-SNAPSHOT, com.willshex:willshex-gson:jar:1.0-SNAPSHOT, com.willshex:willshex-gson-web-service:jar:1.0-SNAPSHOT, com.willshex:willshex-gson-web-service-appengine:jar:1.0-SNAPSHOT, com.willshex:willshex-server:jar:1.0-SNAPSHOT, com.willshex:willshex-service:jar:1.0-SNAPSHOT: Could not find artifact org.commonjava.googlecode.markdown4j:markdown4j-gwt:jar:1.1-SNAPSHOT -> [Help 1]

**Comment by billy1380** [comment]
Hi rajesh99,
You will have to build the dependencies since they are not on mvn centeral.
All the dependencies are open source and can be found here https://github.com/WillShex or under the billy1380 account. I need to put up some build instructions at some point.

**Comment by rajesh99** [comment]
Is there a plan to put dependencies on mvn central in the near term. or when you plan to write the build instructions?

Does the project use GWT - RPC for getting data from the server?

Thanks
Rajesh.

**Comment by billy1380** [comment]
I don't really want to put them on maven central, I much prefer a script for setup.
The script would go through the dependencies...
Get them from __Github__ `git clone ...`
Call `mvn install` on each
Then launch the site `gwt:clean gwt:compile gwt:run-codeserver` and `appengine:devserver`

No immediate plans to do that... but now that I think about it... I might do a test in the next couple of weeks and see how far I get.

I am on Linux so I will probably using bash for this (will work on linux and mac) then add a windows script later (i.e. no plans).

The site does not use GWT-RPC, just standard JSON over http (nothing special).

**Comment by billy1380** [comment]
Rajesh, I have added and install dependencies script and some instructions on how to setup on the home page. Please take a look and let me know whether this works for you.
